# Debezium Server: same Postgres -> AWS Kinesis (cloud path). Credentials come from .env.aws (written by deploy.sh).
debezium.sink.type=kinesis
debezium.sink.kinesis.region=${AWS_REGION:me-central-1}

debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector
debezium.source.offset.storage.file.filename=/tmp/offsets.dat
debezium.source.offset.flush.interval.ms=1000
debezium.source.database.hostname=postgres
debezium.source.database.port=5432
debezium.source.database.user=postgres
debezium.source.database.password=postgres
debezium.source.database.dbname=marketplace
debezium.source.topic.prefix=mkt
debezium.source.table.include.list=public.listings
debezium.source.plugin.name=pgoutput
debezium.source.slot.name=dbz_aws
debezium.source.publication.name=dbz_aws_pub
debezium.source.publication.autocreate.mode=filtered
debezium.source.snapshot.mode=no_data
debezium.source.decimal.handling.mode=double
debezium.source.tombstones.on.delete=false

debezium.format.key=json
debezium.format.key.json.schemas.enable=false
debezium.format.value=json
debezium.format.value.json.schemas.enable=false

# every table -> one Kinesis stream
debezium.transforms=route
debezium.transforms.route.type=org.apache.kafka.connect.transforms.RegexRouter
debezium.transforms.route.regex=.*
debezium.transforms.route.replacement=mkt-cdc
